### ISSUE TITLE
NG18 - onClick

### ISSUE THREAD

**Issue by Stan92** [kamilfurtak/ng-openlayers#5]
Hi,
I have some troubles using the onClick method
it seems it doesn't work.
And by the way, could you tell me which package I have to install to get the ol api tools?
With the ngx-openlayers package I used to use 
import * as ol from "openlayers";
Thanks

```
  <aol-map (onClick)="mapClick($event)" [width]="'500px'"  [height]="'300px'" >
              <aol-interaction-default></aol-interaction-default>
         ....
  </aol-map>
```

**Comment by kamilfurtak** [comment]
Hi,
try use ```olClick``` event, native ```ol``` events has been renamed to more appropriate names.
Also Open Layers library has been updated to 8 version, they changed package name to from ```openlayers ``` to ```ol```, so You should use ```import * as ol from "ol";```.

**Comment by rverberne** [comment]
Hello. I had this small issue as well. The readme says `onClick`, shouldnt this be updated to `olClick` or `onOlClick`?

**Comment by kamilfurtak** [comment]
Hi, thanks for the comment. 
After I forked this repo, there was inconsistent naming convention. 
In next release https://github.com/kamilfurtak/ng-openlayers/pull/4  I'am going to refactor event names according to Angular style guide -> https://angular.dev/style-guide#dont-prefix-output-properties and keep original Open Layers event names.  I'll update event section in readme file.
